training:
  do_train: True
  checkpoint_path:
  batch_size: 24
  max_epoch: 50
  optimizer_name: adam
  lr_scheduler_name:

datamodule:
  dataset:
    feature_types: fbank
    num_mel_bins: 80
    sample_rate: 1600

  dataset_path: E:/datasets/data_thchs30
  batch_size: ${training.batch_size}
  one_dataset: True
  val_set_ratio: 0.05
  test_set_ratio: 0.05
  num_workers: 0
  manifest_path: D:/model/rnn-t/thchs30_manifest/

tokenizer:
  lang: zh
  word_dict_path: D:/model/rnn-t/thchs30_manifest/vocab.txt

logger:
  save_dir: tb_logs
  name: model_logs

model:
  num_classes: ??
  encoder:
    input_dim: 80
    encoder_dim: 512
    num_encoder_layers: 12
    num_attention_heads: 8
    feed_forward_expansion_factor: 4
    conv_expansion_factor: 2
    input_dropout_p: 0.1
    feed_forward_dropout_p: 0.1
    attention_dropout_p: 0.1
    conv_dropout_p: 0.1
    conv_kernel_size: 31
    half_step_residual: True
    joint_ctc_attention: False

  pad_id: 0
  sos_id: 1
  eos_id: 2
  blank_id: 3
  unk_id: 4

  grad_ckpt_batchsize: 4

trainer:
  accelerator: auto
  max_epochs: ${training.max_epoch}
  check_val_every_n_epoch: 5
  log_every_n_steps: 100
  accumulate_grad_batches: 8
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm
  detect_anomaly: True
#  sync_batchnorm: True
#  default_root_dir: ./logs

optimizer:
  lr: 0.001
  betas: [0.9, 0.98]
  weight_decay: 1e-3

lr_scheduler:
  gamma: 0.1
  last_epoch: ${training.max_epoch}



